CREATE ROLE mlflow WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'metadata';

CREATE DATABASE mlflow;

GRANT ALL PRIVILEGES ON mlflow TO mlflow;