FROM python:alpine3.7 
RUN mkdir /python-model-service
COPY . /python-model-service
WORKDIR /python-model-service
RUN apk update
RUN apk add make automake gcc g++ subversion python3-dev
RUN pip3 install -r requirements.txt 
EXPOSE 8888 
ENTRYPOINT [ "python" ] 
CMD [ "app.py" ]  