FROM python:3.7-slim-buster
RUN apt-get update && apt-get upgrade -y && apt-get install -y git
RUN pip3 install mlflow
RUN pip3 install boto3 
RUN pip3 install psycopg2-binary
EXPOSE 5000

# Run tracking uri with postgres backend for metadata
# ENTRYPOINT [ "./startup.sh" ]

# CMD ["mlflow", "server", "--port", "5000", "--host", "0.0.0.0"]