FROM postgres:13

# Initialization shell scripts for mlflow, and google feast
COPY ./mlflow.sql /docker-entrypoint-initdb.d/mlflow.sql
COPY ./feast.sql /docker-entrypoint-initdb.d/feast.sql
COPY ./init-mlflow-db.sh /docker-entrypoint-initdb.d/init-mlflow-db.sh 

RUN chmod +x /docker-entrypoint-initdb.d/mlflow.sql
RUN chmod +x /docker-entrypoint-initdb.d/feast.sql
EXPOSE 5432
