# FROM postgres
FROM postgres:13

# Initialization shell scripts for mlflow backend metadata store
COPY ./mlflow.sql /docker-entrypoint-initdb.d/mlflow.sql
RUN chmod +x /docker-entrypoint-initdb.d/mlflow.sql
# COPY ./init-mlflow-db.sh /docker-entrypoint-initdb.d/init-mlflow-db.sh 
EXPOSE 5432

####### Old ##########
# COPY ./mlflow.sql /docker-entrypoint-initdb.d/mlflow.sql
# RUN chmod +x /docker-entrypoint-initdb.d/mlflow.sql